### ISSUE TITLE
"Invalid input [input {]" & problems with compile

### ISSUE THREAD

**Issue by Pirer12** [mtconnect/dataminer#5]
Hi!

When I want to load the default config then I receive an error.
![image](https://user-images.githubusercontent.com/32102304/110119468-226fad80-7dbc-11eb-8e36-fe1316499939.png)

Moreover, I would like to compile my own dataminer, but the CMake give me these errors. I installed OpenSSL from Chocolatey.
![image](https://user-images.githubusercontent.com/32102304/110119764-86927180-7dbc-11eb-9de3-9c1a9f710367.png)

**Comment by simonyg** [comment]
1. Something is not right about your configuration. Can you attach your configuration file MTDataminer.conf
2. Have not used Chocolately. But one thing to look for is if they support static link. If not, change the CMakeLists.txt to match your installed version.

**Comment by Pirer12** [comment]
Thanks for the response :)
1. I used the default config.
[MTDataminer.zip](https://github.com/mtconnect/dataminer/files/6096077/MTDataminer.zip)

2. Okay, I will try to do something with that. Thanks for your suggestions.

**Comment by simonyg** [comment]
1. The config file you used is for LogStash. The example one for the dataminer is called data miner.cfg.example. Make sure you update its content for your MTConnect agent. 

Its format is <output location>, <MTConnect url>, <poll frequency>. Like
 /tmp,https://smstestbed.nist.gov/vds,60

2. Good chance that it is because you are using VC. Update CMakeLists.txt to match the right default libraries. I made everything static so the prebuilt binaries do not have other dependencies.
